### ISSUE TITLE
Proposal: Make lli and ssi optioal

### ISSUE THREAD

**Issue by VOMAY** [scivision/georinex#20]
Dear Scivision,

Your Rinex3 parser does not only read all observations, but also all lli and ssi indicators. Both come with every phase observation and are stored as floats. They take up a large share of the output xarray size.

From my experience, those indicators are irrelevant for most applications.

I propose to make the lli and ssi parsing optional to save memory and potentially also parsing time. Besides, parsing/storing them as integers would make the xarray output more consistent with the nature/definition of the indicators. Personally, I would ignore thr indicators completely.

Thanks for your hard work!

Best Regards
Volker

**Comment by scivision** [comment]
Yes this is now a feature--by default LLI and SSI are off. This provides a factor of 2 speedup at least, and ~ 30% memory savings
