### ISSUE TITLE
Windows compability: crx2rnx

### ISSUE THREAD

**Issue by VOMAY** [scivision/georinex#27]
Dear scivision,

I love the fact that you decided to support Hatanaka compressed files. However, I am struggling to get it to work in my Windows 10 environment. The respective crx2rnx Windows binaries are available [here](http://terras.gsi.go.jp/ja/crx2rnx/RNXCMP_4.0.7_Windows_bcc.zip)

Thanks!
Volker

**Comment by scivision** [comment]
Fixed in https://github.com/scivision/georinex/releases/tag/v1.6.3
This is a bug in Python itself with Windows subprocess that was worked around (was also a problem with the provided binaries you note)

Yes you can use those provided binaries too, but we don't distribute binaries here.
