### ISSUE TITLE
error trying parse seconds in HEADER LABEL "TIME OF FIRST OBS"

### ISSUE THREAD

**Issue by serioca** [scivision/georinex#29]
I got 'string to float conversion error' for some rinex with second in "TIME OF FIRST OBS" AND "TIME OF LAST OBS" records represented without zeroes before the dot. like following:
("    93     1     1     0     0     .000000                  ") 
In this case the program fail trying to convert the string "." into float

I have also found in some rinex the  seconds field set to 60, like following:
("    93     1     1    23    58    60 .000000                ")
while the correct record should be: 
("    93     1     1    23     59    0 .0000000                ")
In this case the program fail trying to construct datetime object because of the seconds cannot be greather than 59

I fixed this two problems modifing the  function obsheader2 of obs2.py module  (both for 'TIME OF FIRST OBS' and 'TIME OF LST OBS' keys) like following:

hdr['t0'] = datetime(year=int(t0s[:6]), month=int(t0s[6:12]), day=int(t0s[12:18]),
  hour=int(t0s[18:24]), minute=int(t0s[24:30]), second=0,
  microsecond=int(float(t0s[30:43]) % 1 * 1000000)) + timedelta(seconds=int(float('0' + t0s[30:36].strip())))

instead of:

hdr['t0'] = datetime(year=int(t0s[:6]), month=int(t0s[6:12]), day=int(t0s[12:18]),
  hour=int(t0s[18:24]), minute=int(t0s[24:30]), second=int(float(t0s[30:36]),
  microsecond=int(float(t0s[30:43]) % 1 * 1000000)) 

does it  possible to put this patch in the official module or do I need to update my local installation?
Regards

Sergio Bruni

**Comment by scivision** [comment]
Fixed by https://github.com/scivision/georinex/releases/tag/v1.6.7.2, thanks
