### ISSUE TITLE
Error reading rinex files

### ISSUE THREAD

**Issue by charlesnuwan92** [scivision/georinex#30]
Hello Michael,

I was trying to read broadcast ephemerides from BKG GNSS data centre.
The rinex files can be downloaded using in the following link 

https://files.fm/u/efm5v89e

when i read the data i get following error

 E NAV data @ ['2018-09-18T00:00:00.000000000' '2018-09-18T00:10:00.000000000'
 '2018-09-18T00:20:00.000000000' '2018-09-18T00:30:00.000000000'
 '2018-09-18T00:40:00.000000000' '2018-09-18T00:50:00.000000000'
 '2018-09-18T01:00:00.000000000' '2018-09-18T01:20:00.000000000'
 '2018-09-18T01:30:00.000000000' '2018-09-18T01:40:00.000000000'
 '2018-09-18T01:50:00.000000000' '2018-09-18T02:00:00.000000000'
 '2018-09-18T02:10:00.000000000' '2018-09-18T02:20:00.000000000'
 '2018-09-18T02:30:00.000000000' '2018-09-18T02:40:00.000000000'
 '2018-09-18T02:50:00.000000000' '2018-09-18T03:20:00.000000000'
 '2018-09-18T03:30:00.000000000' '2018-09-18T03:50:00.000000000'
 '2018-09-18T04:00:00.000000000' '2018-09-18T04:20:00.000000000'
 '2018-09-18T05:10:00.000000000' '2018-09-18T05:20:00.000000000'
 '2018-09-18T06:30:00.000000000' '2018-09-18T06:40:00.000000000'
 '2018-09-18T14:00:00.000000000' '2018-09-18T14:10:00.000000000'
 '2018-09-18T14:20:00.000000000' '2018-09-18T14:30:00.000000000'
 '2018-09-18T14:40:00.000000000' '2018-09-18T14:50:00.000000000'
 '2018-09-18T15:00:00.000000000' '2018-09-18T15:10:00.000000000'
 '2018-09-18T16:30:00.000000000' '2018-09-18T16:40:00.000000000'
 '2018-09-18T16:50:00.000000000' '2018-09-18T17:00:00.000000000'
 '2018-09-18T17:10:00.000000000' '2018-09-18T17:40:00.000000000'] 
is not the same length as the number of fields.

could you please help me look at this tell me what the issue.

**Comment by scivision** [comment]
fixed by v1.6.7.3
