### ISSUE TITLE
Irregular nav3 parsing with GPS data

### ISSUE THREAD

**Issue by oldbridge** [scivision/georinex#36]
The following example contains a RINEX file generated by a Spirent GSS9000 constellation simulator. It contains GPS data with 31 field while the nav3 parser expects 29 field. A workaround is to include 2 spare fields at position 20 and at the end.

[rinex3Nav.zip](https://github.com/scivision/georinex/files/2640018/rinex3Nav.zip)

**Comment by scivision** [comment]
Thanks @oldbridge for this report!

**Comment by scivision** [comment]
Fixed in https://github.com/scivision/georinex/releases/tag/v1.6.9

**Comment by oldbridge** [comment]
Thanks will check it out!
