### ISSUE TITLE
when reading rinex 3.x file for Galileo an exception occurs

### ISSUE THREAD

**Issue by kasc7** [scivision/georinex#37]
-

**Comment by kasc7** [comment]
ValueError: could not convert string to float:

the cause being in the header ionospheric corr when it parses 4 floats where only 3 (a0,a1,a2) are available

**Comment by kasc7** [comment]
If the comments are somewhat weird above., sorry for that, I was not familiar with this github s/w.
(probably I cannot delete comments)

To say it again in this one comment:

When I read a rinex 3 nav file for galileo, I get an ValueError exception. because it parses 4 values and only gets 3. It is as of quite current version in nav3.py / navheader3 function in the list comprehension statement in the later part of the function (coefficients = [ .... for i in range(**4**)]

**Comment by kasc7** [comment]
I attached the galileo rinex nav file (hope I did it correctly:)
[brdc0320.16l.txt](https://github.com/scivision/georinex/files/2771836/brdc0320.16l.txt)

**Comment by scivision** [comment]
Fixed by https://github.com/scivision/georinex/releases/tag/v1.7.1, thanks for uploading the test file
