### ISSUE TITLE
Decimate reading observations

### ISSUE THREAD

**Issue by alainmuls** [scivision/georinex#38]
Dear Michael,

I started working with georinex, big thanks for this packege.

I have a request: is it possible to decimate the observables?

I mean by this that is the observation interval is 1 sec that I want to only read the observables every 5, 10, ... seconds.

Kind regards
Alain

**Comment by scivision** [comment]
Yes it is, I think it is straightforward for me to add this.

**Comment by scivision** [comment]
added in https://github.com/scivision/georinex/releases/tag/v1.9.0
