### ISSUE TITLE
'test_meas_some_missing()' might be incorrect in test_obs3.py

### ISSUE THREAD

**Issue by anand-satnav** [scivision/georinex#44]
The issue is in line 61 of test_obs3.py

`assert S2P.shape == (2, 14)`

After looking at demo3.10o file, I think the shape should be (2, 10) since the measurement 'S2P' is present only in the G satellite system (10 satellites) and should not include the R satellite system (4 satellites)

Correct me if I am wrong

**Comment by scivision** [comment]
Thanks, we will look at this!

**Comment by scivision** [comment]
this was fixed in fd7f814  thanks
