### ISSUE TITLE
Avoid exception when Number of Observation does not match TYPES OF OBSERV

### ISSUE THREAD

**Issue by serioca** [scivision/georinex#50]
i have submitted to georinex.rinexheader a rinex file, attached, that have the following line:
5    C1    P2    L1    L2    D1    D2                  # / TYPES OF OBSERV
Should be possible do not raise exception?

**Comment by scivision** [comment]
This was fixed in ca82ffb

There may still be cases where this fails, but it attempts to adapt to the actual number of observations specified even when the first digit is wrong `5` in your example.
